package frc.robot.constants;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;

import java.util.Map;

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) { 
    public static final ChoreoTraj FullAuto1$1 = new ChoreoTraj(
        "FullAuto1.1",
        1.29705,
        new Pose2d(4.116, 6.643, Rotation2d.fromRadians(0)),
        new Pose2d(6.198, 5.53, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj FullAuto1$2 = new ChoreoTraj(
        "FullAuto1.2",
        2.95834,
        new Pose2d(6.198, 5.53, Rotation2d.fromRadians(0)),
        new Pose2d(6.115, 1.945, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj ksdjf = new ChoreoTraj(
        "ksdjf",
        1.89075,
        new Pose2d(3.581, 6.355, Rotation2d.fromRadians(0)),
        new Pose2d(6.589, 5.86, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj NewPath = new ChoreoTraj(
        "New Path",
        2.08276,
        new Pose2d(6.074, 6.087, Rotation2d.fromRadians(0)),
        new Pose2d(7.063, 2.522, Rotation2d.fromRadians(0))
    );

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> all = Map.ofEntries(
        Map.entry("FullAuto1.1", FullAuto1$1),
        Map.entry("FullAuto1.2", FullAuto1$2),
        Map.entry("ksdjf", ksdjf),
        Map.entry("New Path", NewPath)
    );
}