package frc.robot.constants;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;

import java.util.Map;

/**
 * A class containing the start pose, end pose, and total time of every Choreo trajectory.
 * This allows for your robot code to access this data without overhead from parsing JSON.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public final class ChoreoTrajData {
    public record TrajectoryData(double totalTimeSecs, Pose2d initialPoseBlue, Pose2d endPoseBlue) {}

    /** Fetches the data corresponding to a specific trajectory. */
    public static TrajectoryData get(String trajName) {
        return data.get(trajName);
    }

    private static final Map<String, TrajectoryData> data = Map.ofEntries(
        Map.entry(
            "Test Path",
            new TrajectoryData(
                2.67254,
                new Pose2d(2.2, 1.141, Rotation2d.fromRadians(0)),
                new Pose2d(7.063, 1.079, Rotation2d.fromRadians(-1.037))
            )
        )
    );

    private ChoreoTrajData() {}
}
  