package frc.robot.constants;

/**
 * A class containing the names of all trajectories created in the Choreo GUI.
 * This allows for references to non-existent or deleted trajectories
 * to be caught at compile time. DO NOT MODIFY THIS FILE YOURSELF!
 * It is automatically generated by Choreo.
 */
public final class ChoreoTrajNames {
    public static final String TestPath = "Test Path";

    private ChoreoTrajNames() {}
}