package frc.chargers.hardware;

import org.littletonrobotics.junction.AutoLog;

/**
 * Represents input data read from a group of motors. <br />
 * You should almost always use the {@link MotorDataAutoLogged} class,
 * which is generated by the @AutoLog annotation after running the code.
 * <pre><code>{@literal
 * // The only exception is in inheritance(don't extend MotorDataAutoLogged).
 * @AutoLog
 * static class ElevatorData extends MotorData {
 *     public boolean limitSwitchHit = false;
 * }
 * private final TalonSignals signals = new TalonSignals(...);
 * void refreshData(ElevatorDataAutoLogged data) {
 *     signals.refresh(data);
 *     data.limitSwitchHit = limitSwitch.get();
 * }
 * }</code></pre>
 */
@AutoLog
public class MotorData {
    public String errorAsString = "";
    public double positionRad = 0;
    public double velocityRadPerSec = 0;
    public double appliedVolts = 0;
    public double[] tempCelsius = new double[1];
    public double[] supplyCurrent = new double[1];
    public double[] torqueCurrent = new double[1];

    public boolean hasErr() {
        return !errorAsString.isEmpty();
    }

    public void setNumMotors(int length) {
        if (tempCelsius.length == length) return;
        tempCelsius = new double[length];
        supplyCurrent = new double[length];
        torqueCurrent = new double[length];
    }

    /** Use {@link MotorDataAutoLogged}, unless if you are inheriting from this class. */
    protected MotorData() {}
}
